FROM node:lts-alpine

ENV PORT 3000

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json /usr/src/app/
RUN yarn install

# Copying source files
COPY . /usr/src/app

ENV NEXT_TELEMETRY_DISABLED=1
ENV CHECKPOINT_DISABLE=1

# Building app
RUN yarn prisma generate
RUN yarn run build
EXPOSE 3000

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

ADD start.sh /start
RUN chmod +x /start

# Running the app
CMD /wait && /start
